export enum Roles {
  SUPERADMIN, //READ WRITE ALL TABEL ALL RECORDS
  ADMIN, //READ WRITE ALL TABLE AND RECORDS ONLY ASSOCIATE FRANCHISE
  READ, //ONLY READALL TABLE
  EMP, // LIMITED PRIVILEDGE
  INVENTORYREAD, // ONLY ABLE TO READ ITEMS AND ITS SELLING PRICE
  CLIENT, // ONLY ABLE TO READ ITEMS AND ITS SELLING PRICE NO OTHER CHANGE
}
